### ISSUE TITLE
An instance of interface that is a readonly field of class is not supported by computed property.

### ISSUE THREAD

**Issue by DingpingZhang** [DingpingZhang/WpfExtensions#4]
See below for detail:

![image](https://user-images.githubusercontent.com/8541016/125237969-622f3000-e29b-11eb-9194-9ee8a58ece85.png)

```
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.<>c__DisplayClass8_0.<VisitMember>b__0()
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.GetOrCreateNode[T](T node, Func`1 creator)
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.<>n__2(MethodCallExpression node)
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.<>c__DisplayClass11_0.<VisitMethodCall>b__0()
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.VisitInContext(Func`1 visitCallback, Context context)
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.VisitVirtualNode(Func`1 visitMethod, Expression node)
   at WpfExtensions.Binding.Expressions.SingleLineLambdaVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at WpfExtensions.Binding.Expressions.ExpressionObserver.GenerateDependencyGraph[T](Expression`1 expression)
   at WpfExtensions.Binding.Expressions.ExpressionObserver.Observes[T](Expression`1 expression, Action`2 onValueChanged)
   at WpfExtensions.Binding.BindableBase.ComputedInternal[T,TOut](Expression`1 expression, TOut fallback, String propertyName)
   at WpfExtensions.Binding.BindableBase.Computed[T](Expression`1 expression, String propertyName)
   at HandyIpcDemo.MainWindowViewModel.get_AddResult() in C:\Users\xxx\source\repos\HandyIpcDemo\HandyIpcDemo\MainWindow.vm.cs:line 28
```

**Comment by DingpingZhang** [comment]
fixed
